/**
 * Shared Styled Components Barrel Export - Clean Import Interface
 * Centralizes all styled components with proper prefixes to avoid conflicts
 */

// Theme Builder Styled Components (Prefixed: Theme*)
export {
  TabContainer,
  Tab,
  ContentContainer,
  SettingsGrid,
  SettingCard,
  SettingGroup,
  Label,
  SelectInput,
  TextInput,
  RangeSlider,
  TextArea,
  PresetButton,
  ActionBar,
  ActionButton as ThemeActionButton,
  ToggleSwitch,
  ColorInput,
  FileInput,
  ImagePreview,
  CollapsibleSection,
  SectionHeader,
  SectionContent,
  ValidationMessage,
  PreviewContainer as ThemePreviewContainer,
  CustomCSSEditor,
  ProgressIndicator,
  TooltipWrapper as ThemeTooltipWrapper,
  QuickActionButton,
  ImportExportPanel,
  ThemePreviewCard
} from './ThemeBuilderStyledComponents';

// Chart Styled Components (Prefixed: Chart*)
export {
  Section as ChartSection,
  SectionTitle as ChartSectionTitle,
  ChartContainer,
  DataGrid,
  MetricCard,
  MetricValue,
  MetricLabel,
  ChartTab,
  TabButton,
  TimeframeTab,
  TimeframeButton,
  ExportButton as ChartExportButton,
  SaveButton,
  InsightBox,
  LoadingOverlay as ChartLoadingOverlay,
  LoadingSpinner as ChartLoadingSpinner,
  StatusMessage as ChartStatusMessage,
  ChartWrapper,
  ResponsiveGrid as ChartResponsiveGrid,
  ButtonGroup as ChartButtonGroup,
  VisuallyHidden as ChartVisuallyHidden,
  FocusTrap as ChartFocusTrap,
  AnimationDelay as ChartAnimationDelay,
  ThemeTransitionWrapper as ChartThemeTransitionWrapper
} from './ChartStyledComponents';

// AI Assistant Styled Components (Prefixed: AI*)
export {
  AssistantContainer,
  AssistantHeader,
  HeaderTitle,
  HeaderActions,
  IconButton,
  AssistantContent,
  ContentSection as AIContentSection,
  ProcessingContainer,
  SpinnerIcon,
  ProcessingText,
  SuggestionsList,
  NoSuggestionsContainer,
  SuccessIcon,
  StatusMessage as AIStatusMessage,
  StatusDescription,
  TipsSection,
  TipsHeader,
  MultiColumnLayout,
  TipContainer,
  TipTitle,
  TipContent,
  FeedbackContainer,
  FeedbackText,
  FeedbackActions,
  FeedbackButton,
  AnalyticsSection,
  AnalyticsTitle,
  AnalyticsGrid,
  AnalyticsMetric,
  AnalyticsValue,
  AnalyticsLabel,
  VisuallyHidden as AIVisuallyHidden,
  FocusTrap as AIFocusTrap,
  ScrollContainer
} from './AIAssistantStyledComponents';

// Preview Panel Styled Components (Prefixed: Preview*)
export {
  Section as PreviewSection,
  SectionTitle as PreviewSectionTitle,
  PreviewControlsContainer,
  PreviewControls,
  PreviewButton,
  ButtonGroup as PreviewButtonGroup,
  ActionButton as PreviewActionButton,
  DownloadButton,
  PDFButton,
  PreviewContainer,
  HeaderSection,
  LogoContainer,
  HeaderContent,
  HeaderTitle as PreviewHeaderTitle,
  HeaderSubtitle,
  ContentSection as PreviewContentSection,
  ContentSectionHeader,
  LoadingOverlay as PreviewLoadingOverlay,
  LoadingSpinner as PreviewLoadingSpinner,
  StatusIndicator,
  ContactSection,
  ContactInfo,
  ContactItem,
  ContactLabel,
  ContactValue,
  NotesSection,
  NotesContent,
  DailyReportsSection,
  DailyReportItem,
  DailyReportHeader,
  DailyReportDay,
  DailyReportContent,
  SecurityCodeBadge,
  VisuallyHidden as PreviewVisuallyHidden,
  FocusTrap as PreviewFocusTrap,
  ResponsiveGrid as PreviewResponsiveGrid,
  ResponsiveText,
  AnimationDelay as PreviewAnimationDelay,
  ThemeTransitionWrapper as PreviewThemeTransitionWrapper,
  SkeletonLoader,
  ScrollContainer as PreviewScrollContainer,
  TooltipWrapper as PreviewTooltipWrapper
} from './PreviewStyledComponents';
